version: '3'

services:
  docker-postal:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-postal
    container_name: docker-postal
    restart: unless-stopped
    networks:
      - postal-network

volumes:
  postal-stor:

networks:
  postal-network:
    driver: bridge